spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lawhan_market
    username: lawhan_market
    password: lawhan_market
  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
